### ISSUE TITLE
脚本不会自动停止

### ISSUE THREAD

**Issue by Liuruyong** [lvdaqian/fastlane-buggly#1]
INFO [2018-05-24 15:36:40.66]: ▸ % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
INFO [2018-05-24 15:36:40.66]: ▸ Dload  Upload   Total   Spent    Left  Speed

会一直卡在这个地方。
去buggly网站查看，dSYM文件已经正确上传了。
最近才出现的这个问题，之前用着没问题

**Comment by lvdaqian** [comment]
@Liuruyong 没想到这个半成品还有人用。 十分感谢~

你现在还是会出现这个问题吗？ 看上去是服务器没有返回。curl 没有结束。

我有空验证一下~。
